"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Preloader from "@/component/Preloader";
import { motion, AnimatePresence } from "framer-motion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Events OC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`antialiased ${geistSans.variable} ${geistMono.variable} bg-black`}>
        {/* Preloader always on top */}
        {/* <Preloader /> */}

        {/* Page fade-in after preloader */}
        <AnimatePresence mode="wait">
          <motion.main
            key="page"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 2.5, duration: 1.2, ease: "easeInOut" }}
          >
            {children}
          </motion.main>
        </AnimatePresence>
      </body>
    </html>
  );
}
